### ISSUE TITLE
iam getting this error sir 

### ISSUE THREAD

**Issue by AndyBezo** [jspw/VS-Code-Config#22] opened 2024-01-13 04:01 UTC
*  Executing task:  copy "C:\Users\shaik\OneDrive\Documents\New folder\hello.cpp" 'C:\Users\shaik\OneDrive\Documents\New folder\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp 

bash: copy: command not found

 *  The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-i', '-c', ' copy "C:\Users\shaik\OneDrive\Documents\New folder\hello.cpp" 'C:\Users\shaik\OneDrive\Documents\New folder\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by jspw** [comment] 2024-01-13 18:46
Please give me some more details like where is the input.txt and output.txt file and the cpp file that you want to run. Also double check you are using "cmd" as default terminal in your vscode console. @AndyBezo

**Comment by AndyBezo** [comment] 2024-01-14 02:07
The issue is resolved after changing the default terminal git bash to cmd
Thank you for the vs code setup, it is very helpful

**Comment by jspw** [comment] 2024-01-14 07:33
most welcome @AndyBez.  As the problem is fixed (which is not a repo issue), I am closing the issue.

**Closed** 2024-01-14 07:33 UTC
